spring.application.name=Mini-project-spring

mybatis.type-handlers-package=org.example.miniprojectspring


spring.datasource.url=jdbc:postgresql://localhost:5432/springminiproject
spring.datasource.username=postgres
spring.datasource.password=8899




#Minio config
minio.url=http://localhost:9000
minio.access-key=RnxRjQ17kH8S271ZPCuz
minio.secret-key=LrNAhyeh5ADDHofodDz3bpvLKXDWav2KmdjFoEEu
minio.bucket-name=pvh-bucket-02

# Multipart file size limits
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB


