spring.application.name=Mini-project-spring
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/springminiproject
spring.datasource.password=8899
spring.datasource.username=postgres

mybatis.type-handlers-package=org.example.miniprojectspring

#Config Mail Sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sengn5112@gmail.com
spring.mail.password=nrar qobj qwnm ddkz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



#Minio config
minio.url=http://localhost:9000
minio.access-key=RnxRjQ17kH8S271ZPCuz
minio.secret-key=LrNAhyeh5ADDHofodDz3bpvLKXDWav2KmdjFoEEu
minio.bucket-name=pvh-bucket-02

# Multipart file size limits
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB


