spring.application.name=Mini-project-spring



mybatis.type-handlers-package=org.example.miniprojectspring

#Config Mail Sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sengn5112@gmail.com
spring.mail.password=nrar qobj qwnm ddkz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#Minio config
minio.url=http://localhost:9000
minio.access-key=SJcDRtcfLYcySHyhbQiz
minio.secret-key=T80Luvlisg2Pl9KOC1joc8aq613nAUsJkRv4ahk7
minio.bucket-name=pvh-bucket-02

# Multipart file size limits
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB


spring.datasource.url=jdbc:postgresql://localhost:5432/springminiproject
spring.datasource.username=postgres
spring.datasource.password=sovanara-181004
jwt.secret=your_secret_key_here
jwt.expiration=86400000


